import type { BiteMenuItem, BiteRestaurant } from "@/types/bites";

export const DEMO_RESTAURANTS: Record<string, { restaurant: BiteRestaurant; menu: BiteMenuItem[] }> = {
  cfa: {
    restaurant: {
      name: "Chick-fil-A",
      cuisine: ["Chicken", "Fast"],
      address: "1000 Cumberland Mall SE, Atlanta, GA 30339",
      lat: 33.8804,
      lng: -84.4627,
      phone: "+14045551234",
      isOpen: true,
      openHours: {},
      deliveryFee: 3.99,
      estimatedTime: "25–35 min",
      rating: 4.8,
      priceRange: "$$",
      tags: ["Chicken", "Salads"],
      imageUrl: "",
      areaOrdersToday: 47,
      neighborCount: 3,
      topItemName: "Spicy Deluxe",
    },
    menu: [
      {
        name: "Spicy Deluxe Sandwich",
        description: "A boneless breast, seasoned, breaded, pressure cooked in refined peanut oil.",
        price: 7.29,
        category: "Entrées",
        imageUrl: "",
        isAvailable: true,
        calories: 550,
        tags: ["spicy"],
        gridditCount: 120,
        orderCount: 890,
        certified: true,
      },
      {
        name: "Waffle Potato Fries",
        description: "Waffle-shaped potatoes, fried.",
        price: 2.65,
        category: "Sides",
        imageUrl: "",
        isAvailable: true,
        calories: 360,
        tags: ["side"],
        gridditCount: 40,
        orderCount: 500,
      },
    ],
  },
  wingstop: {
    restaurant: {
      name: "Wingstop",
      cuisine: ["Wings", "Fries"],
      address: "3200 Cobb Pkwy SE, Atlanta, GA 30339",
      lat: 33.8741,
      lng: -84.4551,
      phone: "+14055559876",
      isOpen: true,
      openHours: {},
      deliveryFee: 4.29,
      estimatedTime: "30–45 min",
      rating: 4.5,
      priceRange: "$$",
      tags: ["Wings", "Late night"],
      imageUrl: "",
      areaOrdersToday: 31,
      neighborCount: 2,
      topItemName: "Lemon Pepper",
    },
    menu: [
      {
        name: "Classic Lemon Pepper Wings",
        description: "8 pc · extra crispy",
        price: 12.99,
        category: "Wings",
        imageUrl: "",
        isAvailable: true,
        calories: 720,
        tags: ["lemon"],
        gridditCount: 200,
        orderCount: 1200,
        certified: true,
      },
      {
        name: "Seasoned Fries",
        description: "Large",
        price: 4.49,
        category: "Sides",
        imageUrl: "",
        isAvailable: true,
        calories: 420,
        tags: [],
        gridditCount: 10,
        orderCount: 300,
      },
    ],
  },
};

export function listDemoRestaurantIds() {
  return Object.keys(DEMO_RESTAURANTS);
}
